[workspace]
resolver = "3"
members = ["aether-broker", "aether-client", "aether-worker"]

[workspace.dependencies]
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = "0.8.6"
tower = "0.5.2"
anyhow = "1"
