[package]
name = "aether-common"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tower.workspace = true
uuid.workspace = true
